mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('selectradioproject.urls')),
    ]

mysite/selectradioproject/urls.py
from django.urls import path
from . import views

app_name = 'selectradioproject'
urlpatterns = [
    path("selectradioprojectPage/",views.selectradioprojectPage,name="selectradioprojectPage"),
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/detail/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    ]

mysite/selectradioproject/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')
    def __str__(self) -> str:
        return self.question_text
    @admin.display(boolean = True,
                   ordering = 'pub_date',
                   description = 'Published recntly?',
                   )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes  = models.IntegerField(default = 0)
    def __str__(self) -> str:
        return self.choice_text
    
class Program(models.Model):
    choice = models.ForeignKey(Choice,on_delete = models.CASCADE)
    program_text = models.CharField(max_length = 200)
    def __str__(self) -> str:
        return self.program_text

mysite/selectradioproject/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from .models import Question,Choice,Program

def selectradioprojectPage(request):
    return HttpResponse('radioproject select Page')

class ResultsView(generic.DetailView):
    model = Choice
    template_name = "selectradioproject/results.html"

def vote(request,question_id):
    question = get_object_or_404(Question,pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST["choice"])
    except (KeyError,Choice.DoesNotExist):
        return render(request,"selectradioproject/detail.html",
                      {"question":question,
                       "error_message":"You didn't select a choice"},
                    )
    else:
        selected_choice.votes = F("votes") +1
        selected_choice.save()
        return HttpResponseRedirect(reverse("selectradioproject:results",args = (question.id,)))
        
class IndexView(generic.ListView):
    template_name = "selectradioproject/index.html"
    context_object_name = "latest_question_list"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = "selectradioproject/detail.html"

mysite/selectradioproject/templates/selectradioproject/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'selectradioproject/style.css'%}" type="text/css" />
    <link
      rel="stylesheet"
      href="{% static 'selectradioproject/style2.css' %}"
      type="text/css"
    />
    <title>Detail</title>
  </head>
  <body>
    <div class="title">
      <h1>{{ question.question_text }}</h1>
    </div>
    {%if question.id%}
    <div style="margin-left: 39px;">
      <form action="{% url 'selectradioproject:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
          {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
          <label for="choice{{ forloop.counter }}" class="choice_text">{{ choice.choice_text }}</label><br>
          {% endfor %}
        </fieldset>
<div style="display: flex;">
  <a href="{% url 'selectradioproject:index'%}" class="back">back</a>
  <div style="margin: 5rem;"></div>
  <input type="submit" value="Select" class="submit">
</div>
      </fieldset>
    </form> 
    {%else%}
    <p>No question available.</p>
    {%endif%}
  </div>
  </body>
  </html>
  

mysite/selectradioproject/templates/selectradioproject/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'selectradioproject/style.css'%}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'selectradioproject/style2.css' %}"
      type="text/css"
    />
    <title>Index</title>
  </head>
  <body>
    <div class="title">
      <h1 class="index">SelectradioProgram</h1>
      <img
        src="{% static 'selectradioproject/svg/redhair-svgrepo-com.svg'%}"
        alt="Red Hair SVG"
        id="redhair"
      />
    </div>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}

      <div class="question_box">
        <button class="question">
          <span class="crayon">
            <a href="{% url 'selectradioproject:detail' question.id %}"
              >{{ question.question_text }}</a
            >
          </span>
        </button>
        {% endfor %}
      </div>
    </ul>
    {% else %}
    <p>No selectradioproject available</p>
    {% endif %}
  </body>
</html>

mysite/selectradioproject/templates/selectradioproject/results.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'selectradioproject/style.css'%}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'selectradioproject/style2.css' %}"
      type="text/css"
    />
    <title>Results</title>
  </head>
  <body class="result_body">
    {%if choice.id%}
    <h3>{{choice.choice_text}}</h3>
    {%for program in choice.program_set.all%}
    <p>{{program.program_text}}</p>
    {%endfor%}
    <a href="{% url 'selectradioproject:detail' choice.id %}">
      select another choice
    </a>
    {%else%}
    <p>No Choice available</p>
    {%endif%}
  </body>
</html>